//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONVERSATION
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> LASTSEEN { get; set; }
        public Nullable<System.DateTime> STARTED { get; set; }
        public string SUBJECT { get; set; }
        public string USERIDs { get; set; }
        public Nullable<int> MessageIDs { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Message Message { get; set; }
    }
}
