//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db562cddb93b5540c7ac57a71600deabc4Entities1 : DbContext
    {
        public db562cddb93b5540c7ac57a71600deabc4Entities1()
            : base("name=db562cddb93b5540c7ac57a71600deabc4Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CATAGORY> CATAGORies { get; set; }
        public virtual DbSet<CONVERSATION> CONVERSATIONs { get; set; }
        public virtual DbSet<EXPERT> EXPERTs { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<POST> POSTs { get; set; }
        public virtual DbSet<PROJECT> PROJECTs { get; set; }
        public virtual DbSet<SPECIALTY> SPECIALTies { get; set; }
    }
}
