//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPECIALTY
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string expertID { get; set; }
    
        public virtual EXPERT EXPERT1 { get; set; }
    }
}
