CREATE TABLE [DBO].[CONVERSATION](
[ID] INT PRIMARY KEY CLUSTERED NOT NULL,
[LASTSEEN] DATETIME,
[STARTED] DATETIME,
[SUBJECT] NVARCHAR(128),

[USERIDs] NVARCHAR(128) FOREIGN KEY REFERENCES [ASPNETUSERS] (ID),
[USERIDs] NVARCHAR(128) FOREIGN KEY REFERENCES [MESSAGE] (ID),
)



CREATE TABLE [DBO].[Message](
[ID] INT PRIMARY KEY CLUSTERED NOT NULL,
[USERID] NVARCHAR(128) UNIQUE FOREIGN KEY REFERENCES [ASPNETUSERS] (ID) NOT NULL,
[ConversationID] INT UNIQUE FOREIGN KEY REFERENCES [CONVERSATION] NOT NULL,
[DATETIMEMADE] DATETIME NOT NULL,
[TEXT] NVARCHAR(MAX) NULL DEFAULT(''),


)

ALTER TABLE [DBO].[EXPERT]
	ADD [VALIDATED] BIT NULL DEFAULT (0)
 






